var modules =
[
    [ "SDTAnalysis.h: Sound analysis tools", "group__analysis.html", "group__analysis" ],
    [ "SDTCommon.h: Common variables and functions", "group__common.html", "group__common" ],
    [ "SDTCommonMacros.h: Macros", "group__commonmacros.html", "group__commonmacros" ],
    [ "SDTComplex.h: Handling complex numbers", "group__complex.html", "group__complex" ],
    [ "SDTControl.h: Compound solid interactions", "group__control.html", "group__control" ],
    [ "SDTDCMotor.h: Electric motors", "group__dcmotor.html", "group__dcmotor" ],
    [ "SDTDemix.h: Transient/tonal/residual components separator", "group__demix.html", "group__demix" ],
    [ "SDTEffects.h: Digital audio effects", "group__effects.html", "group__effects" ],
    [ "SDTFFT.h: Fast Fourier Transform", "group__fft.html", "group__fft" ],
    [ "SDTFilters.h: Audio filters", "group__filters.html", "group__filters" ],
    [ "SDTGases.h: Air turbulence and explosions", "group__gases.html", "group__gases" ],
    [ "SDTInteractors.h: interactions between solids", "group__interactors.html", "group__interactors" ],
    [ "SDTJSON.h: JSON", "group___j_s_o_n.html", "group___j_s_o_n" ],
    [ "SDTLiquids.h: Liquid sounds", "group__liquids.html", "group__liquids" ],
    [ "Modal analyzer", "group__modaltracker.html", "group__modaltracker" ],
    [ "SDTMotor.h: Combustion engines", "group__motor.html", "group__motor" ],
    [ "SDTOSC.h: Open Sound Control", "group___o_s_c.html", "group___o_s_c" ],
    [ "SDTOSCCommon.h: OSC Commons", "group___o_s_c_common.html", "group___o_s_c_common" ],
    [ "SDTOscillators.h: Oscillators", "group__oscillators.html", "group__oscillators" ],
    [ "SDTOSCInteractors.h: OSC Interactors", "group___o_s_c_interactors.html", "group___o_s_c_interactors" ],
    [ "SDTOSCMisc.h: Miscellanea OSC Methods", "group___o_s_c_misc.html", "group___o_s_c_misc" ],
    [ "SDTOSCProjects.h: OSC Projects", "group__osc__projects.html", "group__osc__projects" ],
    [ "SDTOSCResonators.h: OSC Resonators", "group___o_s_c_resonators.html", "group___o_s_c_resonators" ],
    [ "SDTProjects.h: SDT Projects", "group__sdt__projects.html", "group__sdt__projects" ],
    [ "SDTResonators.h: Solid resonators", "group__resonators.html", "group__resonators" ],
    [ "SDTSolids.h: Registering/notifying resonators and interactors", "group__solids.html", "group__solids" ],
    [ "SDTStructs.h: Common data structures", "group__structs.html", "group__structs" ]
];